version: '3.1'

services:
  postgresql:
    image: postgres:11
    #        volumes:
    #          - ./src/test/resources/init.sql:/docker-entrypoint-initdb.d/z_init.sql
    environment:
      - POSTGRES_DB=process
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432