/*
 * This file is generated by jOOQ.
 */
package com.alex.simple.process.jooq;


import com.alex.simple.process.jooq.tables.JProcesses;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PROCESSES_PK = Indexes0.PROCESSES_PK;
    public static final Index PROCESSES_UUID_UINDEX = Indexes0.PROCESSES_UUID_UINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PROCESSES_PK = Internal.createIndex("processes_pk", JProcesses.PROCESSES, new OrderField[]{JProcesses.PROCESSES.UUID}, true);
        public static Index PROCESSES_UUID_UINDEX = Internal.createIndex("processes_uuid_uindex", JProcesses.PROCESSES, new OrderField[]{JProcesses.PROCESSES.UUID}, true);
    }
}
