/*
 * This file is generated by jOOQ.
 */
package com.alex.simple.process.jooq;


import com.alex.simple.process.jooq.tables.JProcesses;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * Таблица хранит данные процессов
     */
    public static final JProcesses PROCESSES = JProcesses.PROCESSES;
}
